services:
  backend:
    build:
      context: .
      dockerfile: ./.compose/local/django/Dockerfile
    image: backend-server-classto-cloud
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env/.env.local
    depends_on:
      - redis
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=classtocloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:latest

  celery_worker:
    build:
      context: .
      dockerfile: ./.compose/local/django/Dockerfile
    image: class-to-cloud-celeary-worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env/.env.local
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./.compose/local/django/Dockerfile
    image: class-to-cloud-celeary-beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env/.env.local
    depends_on:
      - redis
      - db

  # Celeary Dashboard
  flower:
    build:
      context: .
      dockerfile: ./.compose/local/django/Dockerfile
    image: class-to-cloud-celeary-flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/.env.local
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

  # AWS Emulation
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" 
      - "9001:9001" 
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: