# Generated by Django 5.0.6 on 2024-07-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_meta_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='MetaData'),
        ),
    ]
