# Generated by Django 5.0.6 on 2024-07-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_managers_user_is_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='MetaData'),
        ),
        migrations.AlterField(
            model_name='user',
            name='standard',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
