# Generated by Django 5.0.6 on 2024-07-05 05:55

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_alter_batch_uid_alter_chapter_uid_alter_subject_uid'),
        ('lectures', '0004_remove_lecture_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPP',
            fields=[
                ('uid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('file', models.FileField(upload_to=documents.models.dpp_upload_to)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpps', to='batches.batch')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpps', to='batches.chapter')),
                ('lecture', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpps', to='lectures.lecture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('uid', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('file', models.FileField(upload_to=documents.models.note_upload_to)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='batches.batch')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='batches.chapter')),
                ('lecture', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='lectures.lecture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
