# Generated by Django 5.0.6 on 2024-07-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('core', '0005_institute_user_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.institute'),
        ),
    ]
