# Generated by Django 5.0.6 on 2024-07-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='uid',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='uid',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='uid',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
