# Generated by Django 5.0.6 on 2024-07-01 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 7, 1, 19, 2, 35, 455474, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
