# Generated by Django 5.0.6 on 2024-07-02 11:29

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='expires_at',
            field=models.DateTimeField(default=authentication.models.one_hour_default),
        ),
    ]
