# Generated by Django 5.0.6 on 2024-07-04 09:51

import lectures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=lectures.models.video_upload),
        ),
    ]
