# Generated by Django 5.0.6 on 2024-07-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_googlecredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='progress',
        ),
    ]
